version: '3.4'
services:
  words-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/
    command: sh -c "pm2-runtime ./dist/index.js"
    ports:
      - 8080:8000
  words-mongo:
    image: "mongo"
    ports:
      - "27017:27017"